# version: "3.9"
# services:
#   backend:
#     build: ./backend
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./backend:/app
#     depends_on:
#       - db

#   frontend:
#     build: ./frontend
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./frontend:/app

#   db:
#     image: postgres:14-alpine
#     environment:
#       POSTGRES_DB: tasks_db
#       POSTGRES_USER: tasks_user
#       POSTGRES_PASSWORD: tasks_pass
#     ports:
#       - "5432:5432"
version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - DATABASE_NAME=tasks_db
      - DATABASE_USER=tasks_user
      - DATABASE_PASSWORD=tasks_pass
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: tasks_db
      POSTGRES_USER: tasks_user
      POSTGRES_PASSWORD: tasks_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  postgres_data:
